apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx        
    spec:
      containers:
      - name: nginx
        image:  nginx:latest
        resources:
          requests:
            memory: 500Mi
            cpu: 500m
          limits:
            memory: 500Mi
            cpu: 500m
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 20
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 20
          timeoutSeconds: 30
          
